require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-i18n
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - '**/node_modules/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'

I18n/RailsI18n:
  Enabled: true
I18n/GetText:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Not:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
